export {default as Dashboard} from "./Dashboard"
export {default as Artists} from "./Artists"
export {default as Login} from "./Login"
export {default as Redirect} from "./Redirect"
export {default as Tracks} from "./Tracks"
export { default as Playlists } from "./Playlists"
export {default as Podcasts} from "./Podcasts"